gui:
  nerdFontsVersion: "3"
  theme:
    inactiveBorderColor:
      - "#777777"
git:
  branchLogCmd: git log --graph --color=always --date=format:'%Y-%m-%d %H:%M' --pretty=format:'%C(#a0a0a0 reverse)%h%Creset %C(cyan)%ad%Creset %C(#dd4814)%ae%Creset %C(yellow reverse)%d%Creset %n%C(white bold)%s%Creset%n' {{branchName}} --
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never --line-numbers --syntax-theme "Nord"
  log:
    showWholeGraph: true
  allBranchesLogCmds:
    - git log --graph --color=always --date=format:'%Y-%m-%d %H:%M' --pretty=format:'%C(#a0a0a0 reverse)%h%Creset %C(cyan)%ad%Creset %C(#dd4814)%ae%Creset %C(yellow reverse)%d%Creset %n%C(white bold)%s%Creset%n' --
